[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fpdf>=1.7.2",
    "pandas>=2.3.3",
    "streamlit>=1.51.0",
]
